/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: led/led.proto */

#ifndef PROTOBUF_C_led_2fled_2eproto__INCLUDED
#define PROTOBUF_C_led_2fled_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Led__StartPattern Led__StartPattern;
typedef struct _Led__StopPattern Led__StopPattern;


/* --- enums --- */


/* --- messages --- */

/*
 * Message to start a LED pattern
 */
struct  _Led__StartPattern
{
  ProtobufCMessage base;
  char *pattern;
};
#define LED__START_PATTERN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&led__start_pattern__descriptor) \
    , NULL }


/*
 * Message to stop a LED pattern
 */
struct  _Led__StopPattern
{
  ProtobufCMessage base;
  char *pattern;
};
#define LED__STOP_PATTERN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&led__stop_pattern__descriptor) \
    , NULL }


/* Led__StartPattern methods */
void   led__start_pattern__init
                     (Led__StartPattern         *message);
size_t led__start_pattern__get_packed_size
                     (const Led__StartPattern   *message);
size_t led__start_pattern__pack
                     (const Led__StartPattern   *message,
                      uint8_t             *out);
size_t led__start_pattern__pack_to_buffer
                     (const Led__StartPattern   *message,
                      ProtobufCBuffer     *buffer);
Led__StartPattern *
       led__start_pattern__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   led__start_pattern__free_unpacked
                     (Led__StartPattern *message,
                      ProtobufCAllocator *allocator);
/* Led__StopPattern methods */
void   led__stop_pattern__init
                     (Led__StopPattern         *message);
size_t led__stop_pattern__get_packed_size
                     (const Led__StopPattern   *message);
size_t led__stop_pattern__pack
                     (const Led__StopPattern   *message,
                      uint8_t             *out);
size_t led__stop_pattern__pack_to_buffer
                     (const Led__StopPattern   *message,
                      ProtobufCBuffer     *buffer);
Led__StopPattern *
       led__stop_pattern__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   led__stop_pattern__free_unpacked
                     (Led__StopPattern *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Led__StartPattern_Closure)
                 (const Led__StartPattern *message,
                  void *closure_data);
typedef void (*Led__StopPattern_Closure)
                 (const Led__StopPattern *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor led__start_pattern__descriptor;
extern const ProtobufCMessageDescriptor led__stop_pattern__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_led_2fled_2eproto__INCLUDED */
