/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: voice/voice.proto */

#ifndef PROTOBUF_C_voice_2fvoice_2eproto__INCLUDED
#define PROTOBUF_C_voice_2fvoice_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Voice__Status Voice__Status;


/* --- enums --- */


/* --- messages --- */

struct  _Voice__Status
{
  ProtobufCMessage base;
  int32_t status;
};
#define VOICE__STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&voice__status__descriptor) \
    , 0 }


/* Voice__Status methods */
void   voice__status__init
                     (Voice__Status         *message);
size_t voice__status__get_packed_size
                     (const Voice__Status   *message);
size_t voice__status__pack
                     (const Voice__Status   *message,
                      uint8_t             *out);
size_t voice__status__pack_to_buffer
                     (const Voice__Status   *message,
                      ProtobufCBuffer     *buffer);
Voice__Status *
       voice__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   voice__status__free_unpacked
                     (Voice__Status *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Voice__Status_Closure)
                 (const Voice__Status *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor voice__status__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_voice_2fvoice_2eproto__INCLUDED */
