/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: audio/audio.proto */

#ifndef PROTOBUF_C_audio_2faudio_2eproto__INCLUDED
#define PROTOBUF_C_audio_2faudio_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Audio__VolumeUp Audio__VolumeUp;
typedef struct _Audio__VolumeDown Audio__VolumeDown;
typedef struct _Audio__VolumeSet Audio__VolumeSet;
typedef struct _Audio__VolumeGet Audio__VolumeGet;
typedef struct _Audio__PromptPlay Audio__PromptPlay;
typedef struct _Audio__PlayPause Audio__PlayPause;
typedef struct _Audio__SourceSet Audio__SourceSet;
typedef struct _Audio__SourceGet Audio__SourceGet;
typedef struct _Audio__StreamStart Audio__StreamStart;
typedef struct _Audio__StreamStop Audio__StreamStop;
typedef struct _Audio__TrackNext Audio__TrackNext;
typedef struct _Audio__TrackPrevious Audio__TrackPrevious;
typedef struct _Audio__FormatSet Audio__FormatSet;
typedef struct _Audio__FormatGet Audio__FormatGet;


/* --- enums --- */


/* --- messages --- */

/*
 * Volume up event message
 */
struct  _Audio__VolumeUp
{
  ProtobufCMessage base;
  char *source;
  int32_t volume;
};
#define AUDIO__VOLUME_UP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__volume_up__descriptor) \
    , NULL, 0 }


/*
 * Volume down event message
 */
struct  _Audio__VolumeDown
{
  ProtobufCMessage base;
  char *source;
  int32_t volume;
};
#define AUDIO__VOLUME_DOWN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__volume_down__descriptor) \
    , NULL, 0 }


/*
 * Set volume event message
 */
struct  _Audio__VolumeSet
{
  ProtobufCMessage base;
  char *source;
  int32_t port;
  int32_t volume;
};
#define AUDIO__VOLUME_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__volume_set__descriptor) \
    , NULL, 0, 0 }


/*
 * Get volume event message
 */
struct  _Audio__VolumeGet
{
  ProtobufCMessage base;
};
#define AUDIO__VOLUME_GET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__volume_get__descriptor) \
     }


/*
 * Prompt play event message
 */
struct  _Audio__PromptPlay
{
  ProtobufCMessage base;
  char *tone;
  protobuf_c_boolean has_volume;
  int32_t volume;
};
#define AUDIO__PROMPT_PLAY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__prompt_play__descriptor) \
    , NULL, 0, 0 }


/*
 * Play or pause event message
 */
struct  _Audio__PlayPause
{
  ProtobufCMessage base;
  char *source;
  protobuf_c_boolean state;
};
#define AUDIO__PLAY_PAUSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__play_pause__descriptor) \
    , NULL, 0 }


/*
 * Set source event message
 */
struct  _Audio__SourceSet
{
  ProtobufCMessage base;
  char *source;
  int32_t port;
};
#define AUDIO__SOURCE_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__source_set__descriptor) \
    , NULL, 0 }


/*
 * Get source event message
 */
struct  _Audio__SourceGet
{
  ProtobufCMessage base;
};
#define AUDIO__SOURCE_GET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__source_get__descriptor) \
     }


/*
 * Stream start event message
 */
struct  _Audio__StreamStart
{
  ProtobufCMessage base;
  char *source;
  int32_t port;
};
#define AUDIO__STREAM_START__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__stream_start__descriptor) \
    , NULL, 0 }


/*
 * Stream stop event message
 */
struct  _Audio__StreamStop
{
  ProtobufCMessage base;
  char *source;
  int32_t port;
};
#define AUDIO__STREAM_STOP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__stream_stop__descriptor) \
    , NULL, 0 }


/*
 * Next track event message
 */
struct  _Audio__TrackNext
{
  ProtobufCMessage base;
  char *source;
  int32_t port;
};
#define AUDIO__TRACK_NEXT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__track_next__descriptor) \
    , NULL, 0 }


/*
 * Previous track event message
 */
struct  _Audio__TrackPrevious
{
  ProtobufCMessage base;
  char *source;
  int32_t port;
};
#define AUDIO__TRACK_PREVIOUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__track_previous__descriptor) \
    , NULL, 0 }


/*
 * Set audio format event message
 */
struct  _Audio__FormatSet
{
  ProtobufCMessage base;
  int32_t channel;
  int32_t samplerate;
  int32_t bitstream;
};
#define AUDIO__FORMAT_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__format_set__descriptor) \
    , 0, 0, 0 }


/*
 * Get audio format event message
 */
struct  _Audio__FormatGet
{
  ProtobufCMessage base;
};
#define AUDIO__FORMAT_GET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&audio__format_get__descriptor) \
     }


/* Audio__VolumeUp methods */
void   audio__volume_up__init
                     (Audio__VolumeUp         *message);
size_t audio__volume_up__get_packed_size
                     (const Audio__VolumeUp   *message);
size_t audio__volume_up__pack
                     (const Audio__VolumeUp   *message,
                      uint8_t             *out);
size_t audio__volume_up__pack_to_buffer
                     (const Audio__VolumeUp   *message,
                      ProtobufCBuffer     *buffer);
Audio__VolumeUp *
       audio__volume_up__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__volume_up__free_unpacked
                     (Audio__VolumeUp *message,
                      ProtobufCAllocator *allocator);
/* Audio__VolumeDown methods */
void   audio__volume_down__init
                     (Audio__VolumeDown         *message);
size_t audio__volume_down__get_packed_size
                     (const Audio__VolumeDown   *message);
size_t audio__volume_down__pack
                     (const Audio__VolumeDown   *message,
                      uint8_t             *out);
size_t audio__volume_down__pack_to_buffer
                     (const Audio__VolumeDown   *message,
                      ProtobufCBuffer     *buffer);
Audio__VolumeDown *
       audio__volume_down__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__volume_down__free_unpacked
                     (Audio__VolumeDown *message,
                      ProtobufCAllocator *allocator);
/* Audio__VolumeSet methods */
void   audio__volume_set__init
                     (Audio__VolumeSet         *message);
size_t audio__volume_set__get_packed_size
                     (const Audio__VolumeSet   *message);
size_t audio__volume_set__pack
                     (const Audio__VolumeSet   *message,
                      uint8_t             *out);
size_t audio__volume_set__pack_to_buffer
                     (const Audio__VolumeSet   *message,
                      ProtobufCBuffer     *buffer);
Audio__VolumeSet *
       audio__volume_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__volume_set__free_unpacked
                     (Audio__VolumeSet *message,
                      ProtobufCAllocator *allocator);
/* Audio__VolumeGet methods */
void   audio__volume_get__init
                     (Audio__VolumeGet         *message);
size_t audio__volume_get__get_packed_size
                     (const Audio__VolumeGet   *message);
size_t audio__volume_get__pack
                     (const Audio__VolumeGet   *message,
                      uint8_t             *out);
size_t audio__volume_get__pack_to_buffer
                     (const Audio__VolumeGet   *message,
                      ProtobufCBuffer     *buffer);
Audio__VolumeGet *
       audio__volume_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__volume_get__free_unpacked
                     (Audio__VolumeGet *message,
                      ProtobufCAllocator *allocator);
/* Audio__PromptPlay methods */
void   audio__prompt_play__init
                     (Audio__PromptPlay         *message);
size_t audio__prompt_play__get_packed_size
                     (const Audio__PromptPlay   *message);
size_t audio__prompt_play__pack
                     (const Audio__PromptPlay   *message,
                      uint8_t             *out);
size_t audio__prompt_play__pack_to_buffer
                     (const Audio__PromptPlay   *message,
                      ProtobufCBuffer     *buffer);
Audio__PromptPlay *
       audio__prompt_play__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__prompt_play__free_unpacked
                     (Audio__PromptPlay *message,
                      ProtobufCAllocator *allocator);
/* Audio__PlayPause methods */
void   audio__play_pause__init
                     (Audio__PlayPause         *message);
size_t audio__play_pause__get_packed_size
                     (const Audio__PlayPause   *message);
size_t audio__play_pause__pack
                     (const Audio__PlayPause   *message,
                      uint8_t             *out);
size_t audio__play_pause__pack_to_buffer
                     (const Audio__PlayPause   *message,
                      ProtobufCBuffer     *buffer);
Audio__PlayPause *
       audio__play_pause__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__play_pause__free_unpacked
                     (Audio__PlayPause *message,
                      ProtobufCAllocator *allocator);
/* Audio__SourceSet methods */
void   audio__source_set__init
                     (Audio__SourceSet         *message);
size_t audio__source_set__get_packed_size
                     (const Audio__SourceSet   *message);
size_t audio__source_set__pack
                     (const Audio__SourceSet   *message,
                      uint8_t             *out);
size_t audio__source_set__pack_to_buffer
                     (const Audio__SourceSet   *message,
                      ProtobufCBuffer     *buffer);
Audio__SourceSet *
       audio__source_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__source_set__free_unpacked
                     (Audio__SourceSet *message,
                      ProtobufCAllocator *allocator);
/* Audio__SourceGet methods */
void   audio__source_get__init
                     (Audio__SourceGet         *message);
size_t audio__source_get__get_packed_size
                     (const Audio__SourceGet   *message);
size_t audio__source_get__pack
                     (const Audio__SourceGet   *message,
                      uint8_t             *out);
size_t audio__source_get__pack_to_buffer
                     (const Audio__SourceGet   *message,
                      ProtobufCBuffer     *buffer);
Audio__SourceGet *
       audio__source_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__source_get__free_unpacked
                     (Audio__SourceGet *message,
                      ProtobufCAllocator *allocator);
/* Audio__StreamStart methods */
void   audio__stream_start__init
                     (Audio__StreamStart         *message);
size_t audio__stream_start__get_packed_size
                     (const Audio__StreamStart   *message);
size_t audio__stream_start__pack
                     (const Audio__StreamStart   *message,
                      uint8_t             *out);
size_t audio__stream_start__pack_to_buffer
                     (const Audio__StreamStart   *message,
                      ProtobufCBuffer     *buffer);
Audio__StreamStart *
       audio__stream_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__stream_start__free_unpacked
                     (Audio__StreamStart *message,
                      ProtobufCAllocator *allocator);
/* Audio__StreamStop methods */
void   audio__stream_stop__init
                     (Audio__StreamStop         *message);
size_t audio__stream_stop__get_packed_size
                     (const Audio__StreamStop   *message);
size_t audio__stream_stop__pack
                     (const Audio__StreamStop   *message,
                      uint8_t             *out);
size_t audio__stream_stop__pack_to_buffer
                     (const Audio__StreamStop   *message,
                      ProtobufCBuffer     *buffer);
Audio__StreamStop *
       audio__stream_stop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__stream_stop__free_unpacked
                     (Audio__StreamStop *message,
                      ProtobufCAllocator *allocator);
/* Audio__TrackNext methods */
void   audio__track_next__init
                     (Audio__TrackNext         *message);
size_t audio__track_next__get_packed_size
                     (const Audio__TrackNext   *message);
size_t audio__track_next__pack
                     (const Audio__TrackNext   *message,
                      uint8_t             *out);
size_t audio__track_next__pack_to_buffer
                     (const Audio__TrackNext   *message,
                      ProtobufCBuffer     *buffer);
Audio__TrackNext *
       audio__track_next__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__track_next__free_unpacked
                     (Audio__TrackNext *message,
                      ProtobufCAllocator *allocator);
/* Audio__TrackPrevious methods */
void   audio__track_previous__init
                     (Audio__TrackPrevious         *message);
size_t audio__track_previous__get_packed_size
                     (const Audio__TrackPrevious   *message);
size_t audio__track_previous__pack
                     (const Audio__TrackPrevious   *message,
                      uint8_t             *out);
size_t audio__track_previous__pack_to_buffer
                     (const Audio__TrackPrevious   *message,
                      ProtobufCBuffer     *buffer);
Audio__TrackPrevious *
       audio__track_previous__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__track_previous__free_unpacked
                     (Audio__TrackPrevious *message,
                      ProtobufCAllocator *allocator);
/* Audio__FormatSet methods */
void   audio__format_set__init
                     (Audio__FormatSet         *message);
size_t audio__format_set__get_packed_size
                     (const Audio__FormatSet   *message);
size_t audio__format_set__pack
                     (const Audio__FormatSet   *message,
                      uint8_t             *out);
size_t audio__format_set__pack_to_buffer
                     (const Audio__FormatSet   *message,
                      ProtobufCBuffer     *buffer);
Audio__FormatSet *
       audio__format_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__format_set__free_unpacked
                     (Audio__FormatSet *message,
                      ProtobufCAllocator *allocator);
/* Audio__FormatGet methods */
void   audio__format_get__init
                     (Audio__FormatGet         *message);
size_t audio__format_get__get_packed_size
                     (const Audio__FormatGet   *message);
size_t audio__format_get__pack
                     (const Audio__FormatGet   *message,
                      uint8_t             *out);
size_t audio__format_get__pack_to_buffer
                     (const Audio__FormatGet   *message,
                      ProtobufCBuffer     *buffer);
Audio__FormatGet *
       audio__format_get__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   audio__format_get__free_unpacked
                     (Audio__FormatGet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Audio__VolumeUp_Closure)
                 (const Audio__VolumeUp *message,
                  void *closure_data);
typedef void (*Audio__VolumeDown_Closure)
                 (const Audio__VolumeDown *message,
                  void *closure_data);
typedef void (*Audio__VolumeSet_Closure)
                 (const Audio__VolumeSet *message,
                  void *closure_data);
typedef void (*Audio__VolumeGet_Closure)
                 (const Audio__VolumeGet *message,
                  void *closure_data);
typedef void (*Audio__PromptPlay_Closure)
                 (const Audio__PromptPlay *message,
                  void *closure_data);
typedef void (*Audio__PlayPause_Closure)
                 (const Audio__PlayPause *message,
                  void *closure_data);
typedef void (*Audio__SourceSet_Closure)
                 (const Audio__SourceSet *message,
                  void *closure_data);
typedef void (*Audio__SourceGet_Closure)
                 (const Audio__SourceGet *message,
                  void *closure_data);
typedef void (*Audio__StreamStart_Closure)
                 (const Audio__StreamStart *message,
                  void *closure_data);
typedef void (*Audio__StreamStop_Closure)
                 (const Audio__StreamStop *message,
                  void *closure_data);
typedef void (*Audio__TrackNext_Closure)
                 (const Audio__TrackNext *message,
                  void *closure_data);
typedef void (*Audio__TrackPrevious_Closure)
                 (const Audio__TrackPrevious *message,
                  void *closure_data);
typedef void (*Audio__FormatSet_Closure)
                 (const Audio__FormatSet *message,
                  void *closure_data);
typedef void (*Audio__FormatGet_Closure)
                 (const Audio__FormatGet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor audio__volume_up__descriptor;
extern const ProtobufCMessageDescriptor audio__volume_down__descriptor;
extern const ProtobufCMessageDescriptor audio__volume_set__descriptor;
extern const ProtobufCMessageDescriptor audio__volume_get__descriptor;
extern const ProtobufCMessageDescriptor audio__prompt_play__descriptor;
extern const ProtobufCMessageDescriptor audio__play_pause__descriptor;
extern const ProtobufCMessageDescriptor audio__source_set__descriptor;
extern const ProtobufCMessageDescriptor audio__source_get__descriptor;
extern const ProtobufCMessageDescriptor audio__stream_start__descriptor;
extern const ProtobufCMessageDescriptor audio__stream_stop__descriptor;
extern const ProtobufCMessageDescriptor audio__track_next__descriptor;
extern const ProtobufCMessageDescriptor audio__track_previous__descriptor;
extern const ProtobufCMessageDescriptor audio__format_set__descriptor;
extern const ProtobufCMessageDescriptor audio__format_get__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_audio_2faudio_2eproto__INCLUDED */
