/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: source/source.proto */

#ifndef PROTOBUF_C_source_2fsource_2eproto__INCLUDED
#define PROTOBUF_C_source_2fsource_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Source__AirplayStatus Source__AirplayStatus;
typedef struct _Source__SourceSwitch Source__SourceSwitch;


/* --- enums --- */


/* --- messages --- */

/*
 * Airplay status event message
 */
struct  _Source__AirplayStatus
{
  ProtobufCMessage base;
  int32_t status;
};
#define SOURCE__AIRPLAY_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&source__airplay_status__descriptor) \
    , 0 }


/*
 * Source switch event message
 */
struct  _Source__SourceSwitch
{
  ProtobufCMessage base;
  char *source;
};
#define SOURCE__SOURCE_SWITCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&source__source_switch__descriptor) \
    , NULL }


/* Source__AirplayStatus methods */
void   source__airplay_status__init
                     (Source__AirplayStatus         *message);
size_t source__airplay_status__get_packed_size
                     (const Source__AirplayStatus   *message);
size_t source__airplay_status__pack
                     (const Source__AirplayStatus   *message,
                      uint8_t             *out);
size_t source__airplay_status__pack_to_buffer
                     (const Source__AirplayStatus   *message,
                      ProtobufCBuffer     *buffer);
Source__AirplayStatus *
       source__airplay_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   source__airplay_status__free_unpacked
                     (Source__AirplayStatus *message,
                      ProtobufCAllocator *allocator);
/* Source__SourceSwitch methods */
void   source__source_switch__init
                     (Source__SourceSwitch         *message);
size_t source__source_switch__get_packed_size
                     (const Source__SourceSwitch   *message);
size_t source__source_switch__pack
                     (const Source__SourceSwitch   *message,
                      uint8_t             *out);
size_t source__source_switch__pack_to_buffer
                     (const Source__SourceSwitch   *message,
                      ProtobufCBuffer     *buffer);
Source__SourceSwitch *
       source__source_switch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   source__source_switch__free_unpacked
                     (Source__SourceSwitch *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Source__AirplayStatus_Closure)
                 (const Source__AirplayStatus *message,
                  void *closure_data);
typedef void (*Source__SourceSwitch_Closure)
                 (const Source__SourceSwitch *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor source__airplay_status__descriptor;
extern const ProtobufCMessageDescriptor source__source_switch__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_source_2fsource_2eproto__INCLUDED */
