/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: button/button.proto */

#ifndef PROTOBUF_C_button_2fbutton_2eproto__INCLUDED
#define PROTOBUF_C_button_2fbutton_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Button__Pressed Button__Pressed;
typedef struct _Button__Released Button__Released;
typedef struct _Button__SingleClick Button__SingleClick;
typedef struct _Button__DoubleClick Button__DoubleClick;
typedef struct _Button__TripleClick Button__TripleClick;
typedef struct _Button__LongHold Button__LongHold;
typedef struct _Button__VeryLongHold Button__VeryLongHold;


/* --- enums --- */


/* --- messages --- */

/*
 * Button pressed event message
 */
struct  _Button__Pressed
{
  ProtobufCMessage base;
  char *name;
};
#define BUTTON__PRESSED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&button__pressed__descriptor) \
    , NULL }


/*
 * Button released event message
 */
struct  _Button__Released
{
  ProtobufCMessage base;
  char *name;
};
#define BUTTON__RELEASED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&button__released__descriptor) \
    , NULL }


/*
 * Button single click event message
 */
struct  _Button__SingleClick
{
  ProtobufCMessage base;
  char *name;
};
#define BUTTON__SINGLE_CLICK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&button__single_click__descriptor) \
    , NULL }


/*
 * Button double click event message
 */
struct  _Button__DoubleClick
{
  ProtobufCMessage base;
  char *name;
};
#define BUTTON__DOUBLE_CLICK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&button__double_click__descriptor) \
    , NULL }


/*
 * Button triple click event message
 */
struct  _Button__TripleClick
{
  ProtobufCMessage base;
  char *name;
};
#define BUTTON__TRIPLE_CLICK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&button__triple_click__descriptor) \
    , NULL }


/*
 * Button long hold event message
 */
struct  _Button__LongHold
{
  ProtobufCMessage base;
  char *name;
};
#define BUTTON__LONG_HOLD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&button__long_hold__descriptor) \
    , NULL }


/*
 * Button very long hold event message
 */
struct  _Button__VeryLongHold
{
  ProtobufCMessage base;
  char *name;
};
#define BUTTON__VERY_LONG_HOLD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&button__very_long_hold__descriptor) \
    , NULL }


/* Button__Pressed methods */
void   button__pressed__init
                     (Button__Pressed         *message);
size_t button__pressed__get_packed_size
                     (const Button__Pressed   *message);
size_t button__pressed__pack
                     (const Button__Pressed   *message,
                      uint8_t             *out);
size_t button__pressed__pack_to_buffer
                     (const Button__Pressed   *message,
                      ProtobufCBuffer     *buffer);
Button__Pressed *
       button__pressed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   button__pressed__free_unpacked
                     (Button__Pressed *message,
                      ProtobufCAllocator *allocator);
/* Button__Released methods */
void   button__released__init
                     (Button__Released         *message);
size_t button__released__get_packed_size
                     (const Button__Released   *message);
size_t button__released__pack
                     (const Button__Released   *message,
                      uint8_t             *out);
size_t button__released__pack_to_buffer
                     (const Button__Released   *message,
                      ProtobufCBuffer     *buffer);
Button__Released *
       button__released__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   button__released__free_unpacked
                     (Button__Released *message,
                      ProtobufCAllocator *allocator);
/* Button__SingleClick methods */
void   button__single_click__init
                     (Button__SingleClick         *message);
size_t button__single_click__get_packed_size
                     (const Button__SingleClick   *message);
size_t button__single_click__pack
                     (const Button__SingleClick   *message,
                      uint8_t             *out);
size_t button__single_click__pack_to_buffer
                     (const Button__SingleClick   *message,
                      ProtobufCBuffer     *buffer);
Button__SingleClick *
       button__single_click__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   button__single_click__free_unpacked
                     (Button__SingleClick *message,
                      ProtobufCAllocator *allocator);
/* Button__DoubleClick methods */
void   button__double_click__init
                     (Button__DoubleClick         *message);
size_t button__double_click__get_packed_size
                     (const Button__DoubleClick   *message);
size_t button__double_click__pack
                     (const Button__DoubleClick   *message,
                      uint8_t             *out);
size_t button__double_click__pack_to_buffer
                     (const Button__DoubleClick   *message,
                      ProtobufCBuffer     *buffer);
Button__DoubleClick *
       button__double_click__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   button__double_click__free_unpacked
                     (Button__DoubleClick *message,
                      ProtobufCAllocator *allocator);
/* Button__TripleClick methods */
void   button__triple_click__init
                     (Button__TripleClick         *message);
size_t button__triple_click__get_packed_size
                     (const Button__TripleClick   *message);
size_t button__triple_click__pack
                     (const Button__TripleClick   *message,
                      uint8_t             *out);
size_t button__triple_click__pack_to_buffer
                     (const Button__TripleClick   *message,
                      ProtobufCBuffer     *buffer);
Button__TripleClick *
       button__triple_click__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   button__triple_click__free_unpacked
                     (Button__TripleClick *message,
                      ProtobufCAllocator *allocator);
/* Button__LongHold methods */
void   button__long_hold__init
                     (Button__LongHold         *message);
size_t button__long_hold__get_packed_size
                     (const Button__LongHold   *message);
size_t button__long_hold__pack
                     (const Button__LongHold   *message,
                      uint8_t             *out);
size_t button__long_hold__pack_to_buffer
                     (const Button__LongHold   *message,
                      ProtobufCBuffer     *buffer);
Button__LongHold *
       button__long_hold__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   button__long_hold__free_unpacked
                     (Button__LongHold *message,
                      ProtobufCAllocator *allocator);
/* Button__VeryLongHold methods */
void   button__very_long_hold__init
                     (Button__VeryLongHold         *message);
size_t button__very_long_hold__get_packed_size
                     (const Button__VeryLongHold   *message);
size_t button__very_long_hold__pack
                     (const Button__VeryLongHold   *message,
                      uint8_t             *out);
size_t button__very_long_hold__pack_to_buffer
                     (const Button__VeryLongHold   *message,
                      ProtobufCBuffer     *buffer);
Button__VeryLongHold *
       button__very_long_hold__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   button__very_long_hold__free_unpacked
                     (Button__VeryLongHold *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Button__Pressed_Closure)
                 (const Button__Pressed *message,
                  void *closure_data);
typedef void (*Button__Released_Closure)
                 (const Button__Released *message,
                  void *closure_data);
typedef void (*Button__SingleClick_Closure)
                 (const Button__SingleClick *message,
                  void *closure_data);
typedef void (*Button__DoubleClick_Closure)
                 (const Button__DoubleClick *message,
                  void *closure_data);
typedef void (*Button__TripleClick_Closure)
                 (const Button__TripleClick *message,
                  void *closure_data);
typedef void (*Button__LongHold_Closure)
                 (const Button__LongHold *message,
                  void *closure_data);
typedef void (*Button__VeryLongHold_Closure)
                 (const Button__VeryLongHold *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor button__pressed__descriptor;
extern const ProtobufCMessageDescriptor button__released__descriptor;
extern const ProtobufCMessageDescriptor button__single_click__descriptor;
extern const ProtobufCMessageDescriptor button__double_click__descriptor;
extern const ProtobufCMessageDescriptor button__triple_click__descriptor;
extern const ProtobufCMessageDescriptor button__long_hold__descriptor;
extern const ProtobufCMessageDescriptor button__very_long_hold__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_button_2fbutton_2eproto__INCLUDED */
