/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tym.proto */

#ifndef PROTOBUF_C_tym_2eproto__INCLUDED
#define PROTOBUF_C_tym_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "audio/audio.pb-c.h"
#include "button/button.pb-c.h"
#include "connectivity/connectivity.pb-c.h"
#include "devices/devices.pb-c.h"
#include "led/led.pb-c.h"
#include "source/source.pb-c.h"
#include "system/system.pb-c.h"
#include "voice/voice.pb-c.h"

typedef struct _TymMessage TymMessage;


/* --- enums --- */


/* --- messages --- */

typedef enum {
  TYM_MESSAGE__MSG__NOT_SET = 0,
  TYM_MESSAGE__MSG_AUDIO_VOLUME_UP = 1,
  TYM_MESSAGE__MSG_AUDIO_VOLUME_DOWN = 2,
  TYM_MESSAGE__MSG_AUDIO_VOLUME_SET = 3,
  TYM_MESSAGE__MSG_AUDIO_VOLUME_GET = 4,
  TYM_MESSAGE__MSG_AUDIO_PROMPT_PLAY = 5,
  TYM_MESSAGE__MSG_AUDIO_PLAY_PAUSE = 6,
  TYM_MESSAGE__MSG_AUDIO_SOURCE_SET = 7,
  TYM_MESSAGE__MSG_AUDIO_SOURCE_GET = 8,
  TYM_MESSAGE__MSG_AUDIO_STREAM_START = 9,
  TYM_MESSAGE__MSG_AUDIO_STREAM_STOP = 10,
  TYM_MESSAGE__MSG_AUDIO_TRACK_NEXT = 11,
  TYM_MESSAGE__MSG_AUDIO_TRACK_PREVIOUS = 12,
  TYM_MESSAGE__MSG_AUDIO_FORMAT_SET = 13,
  TYM_MESSAGE__MSG_AUDIO_FORMAT_GET = 14,
  TYM_MESSAGE__MSG_BUTTON_PRESSED = 200,
  TYM_MESSAGE__MSG_BUTTON_RELEASED = 201,
  TYM_MESSAGE__MSG_BUTTON_SINGLE_CLICK = 202,
  TYM_MESSAGE__MSG_BUTTON_DOUBLE_CLICK = 203,
  TYM_MESSAGE__MSG_BUTTON_TRIPLE_CLICK = 204,
  TYM_MESSAGE__MSG_BUTTON_LONG_HOLD = 205,
  TYM_MESSAGE__MSG_BUTTON_VERYLONG_HOLD = 206,
  TYM_MESSAGE__MSG_CONNECTIVITY_BT_ENABLED = 400,
  TYM_MESSAGE__MSG_CONNECTIVITY_BT_PAIRING = 401,
  TYM_MESSAGE__MSG_CONNECTIVITY_BT_CONNECTED = 402,
  TYM_MESSAGE__MSG_CONNECTIVITY_WIFI_CONNECTED = 403,
  TYM_MESSAGE__MSG_CONNECTIVITY_WIFI_CONNECT = 404,
  TYM_MESSAGE__MSG_CONNECTIVITY_BT_ENABLE = 405,
  TYM_MESSAGE__MSG_CONNECTIVITY_BT_DISABLE = 406,
  TYM_MESSAGE__MSG_CONNECTIVITY_BT_UNPAIR = 407,
  TYM_MESSAGE__MSG_CONNECTIVITY_WIFI_ERROR = 408,
  TYM_MESSAGE__MSG_CONNECTIVITY_SELF_BT_ENABLED = 409,
  TYM_MESSAGE__MSG_CONNECTIVITY_SELF_BT_PAIRING = 410,
  TYM_MESSAGE__MSG_CONNECTIVITY_SELF_BT_CONNECTED = 411,
  TYM_MESSAGE__MSG_CONNECTIVITY_SELF_WIFI_CONNECTING = 412,
  TYM_MESSAGE__MSG_CONNECTIVITY_SELF_WIFI_CONNECTED = 413,
  TYM_MESSAGE__MSG_CONNECTIVITY_SELF_WIFI_DISCONNECTED = 414,
  TYM_MESSAGE__MSG_CONNECTIVITY_WIFI_SCAN = 415,
  TYM_MESSAGE__MSG_CONNECTIVITY_WIFI_SCANRESULT = 416,
  TYM_MESSAGE__MSG_CONNECTIVITY_WIFI_ONBOARD = 417,
  TYM_MESSAGE__MSG_CONNECTIVITY_WIFI_ONBOARDED = 418,
  TYM_MESSAGE__MSG_DEVICES_ULTRASONIC_STATUS = 600,
  TYM_MESSAGE__MSG_DEVICES_CHARGING_STATE = 601,
  TYM_MESSAGE__MSG_DEVICES_CHARGING_PROTECT = 602,
  TYM_MESSAGE__MSG_DEVICES_BAT_LEVEL_LOW = 603,
  TYM_MESSAGE__MSG_DEVICES_DISPLAY_SET = 604,
  TYM_MESSAGE__MSG_LED_START_PATTERN = 800,
  TYM_MESSAGE__MSG_LED_STOP_PATTERN = 801,
  TYM_MESSAGE__MSG_SOURCE_AIRPLAY_STATUS = 1000,
  TYM_MESSAGE__MSG_SOURCE_SOURCE_SWITCH = 1001,
  TYM_MESSAGE__MSG_SYSTEM_REBOOT = 1200,
  TYM_MESSAGE__MSG_SYSTEM_POWER_ON = 1201,
  TYM_MESSAGE__MSG_SYSTEM_POWER_OFF = 1202,
  TYM_MESSAGE__MSG_SYSTEM_POWER_SUPPLY = 1203,
  TYM_MESSAGE__MSG_SYSTEM_MODE_CHANGING = 1204,
  TYM_MESSAGE__MSG_SYSTEM_GET_UPGRADE_SERVER_VERSION = 1205,
  TYM_MESSAGE__MSG_SYSTEM_UPGRADE_DOWNLOAD = 1206,
  TYM_MESSAGE__MSG_SYSTEM_UPGRADE_INSTALL = 1207,
  TYM_MESSAGE__MSG_SYSTEM_UPGRADE_REBOOT = 1208,
  TYM_MESSAGE__MSG_SYSTEM_UPGRADING = 1209,
  TYM_MESSAGE__MSG_SYSTEM_UPGRADED = 1210,
  TYM_MESSAGE__MSG_SYSTEM_FACTORY_RESET = 1211,
  TYM_MESSAGE__MSG_VOICE_STATUS = 1400
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TYM_MESSAGE__MSG)
} TymMessage__MsgCase;

struct  _TymMessage
{
  ProtobufCMessage base;
  TymMessage__MsgCase msg_case;
  union {
    /*
     * audio group messages
     */
    Audio__VolumeUp *audio_volume_up;
    Audio__VolumeDown *audio_volume_down;
    Audio__VolumeSet *audio_volume_set;
    Audio__VolumeGet *audio_volume_get;
    Audio__PromptPlay *audio_prompt_play;
    Audio__PlayPause *audio_play_pause;
    Audio__SourceSet *audio_source_set;
    Audio__SourceGet *audio_source_get;
    Audio__StreamStart *audio_stream_start;
    Audio__StreamStop *audio_stream_stop;
    Audio__TrackNext *audio_track_next;
    Audio__TrackPrevious *audio_track_previous;
    Audio__FormatSet *audio_format_set;
    Audio__FormatGet *audio_format_get;
    /*
     * button group messages
     */
    Button__Pressed *button_pressed;
    Button__Released *button_released;
    Button__SingleClick *button_single_click;
    Button__DoubleClick *button_double_click;
    Button__TripleClick *button_triple_click;
    Button__LongHold *button_long_hold;
    Button__VeryLongHold *button_verylong_hold;
    /*
     * connectivity group messages
     */
    Connectivity__BtEnabled *connectivity_bt_enabled;
    Connectivity__BtPairing *connectivity_bt_pairing;
    Connectivity__BtConnected *connectivity_bt_connected;
    Connectivity__WifiConnected *connectivity_wifi_connected;
    Connectivity__WifiConnect *connectivity_wifi_connect;
    Connectivity__BtEnable *connectivity_bt_enable;
    Connectivity__BtDisable *connectivity_bt_disable;
    Connectivity__BtUnpair *connectivity_bt_unpair;
    Connectivity__WifiError *connectivity_wifi_error;
    Connectivity__SelfBtEnabled *connectivity_self_bt_enabled;
    Connectivity__SelfBtPairing *connectivity_self_bt_pairing;
    Connectivity__SelfBtConnected *connectivity_self_bt_connected;
    Connectivity__SelfWifiConnecting *connectivity_self_wifi_connecting;
    Connectivity__SelfWifiConnected *connectivity_self_wifi_connected;
    Connectivity__SelfWifiDisconnected *connectivity_self_wifi_disconnected;
    Connectivity__WifiScan *connectivity_wifi_scan;
    Connectivity__WifiScanResult *connectivity_wifi_scanresult;
    Connectivity__WifiOnboard *connectivity_wifi_onboard;
    Connectivity__WifiOnboarded *connectivity_wifi_onboarded;
    /*
     * devices group messages
     */
    Devices__UltrasonicStatus *devices_ultrasonic_status;
    Devices__ChargingState *devices_charging_state;
    Devices__ChargingProtect *devices_charging_protect;
    Devices__BatLevelLow *devices_bat_level_low;
    Devices__DisplaySet *devices_display_set;
    /*
     * led group messages
     */
    Led__StartPattern *led_start_pattern;
    Led__StopPattern *led_stop_pattern;
    /*
     * source group messages
     */
    Source__AirplayStatus *source_airplay_status;
    Source__SourceSwitch *source_source_switch;
    /*
     * system group messages
     */
    System__Reboot *system_reboot;
    System__PowerOn *system_power_on;
    System__PowerOff *system_power_off;
    System__PowerSupply *system_power_supply;
    System__ModeChanging *system_mode_changing;
    System__GetUpgradeServerVersion *system_get_upgrade_server_version;
    System__UpgradeDownload *system_upgrade_download;
    System__UpgradeInstall *system_upgrade_install;
    System__UpgradeInstall *system_upgrade_reboot;
    System__Upgrading *system_upgrading;
    System__Upgraded *system_upgraded;
    System__FactoryReset *system_factory_reset;
    /*
     * voice group messages
     */
    Voice__Status *voice_status;
  };
};
#define TYM_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tym_message__descriptor) \
    , TYM_MESSAGE__MSG__NOT_SET, {0} }


/* TymMessage methods */
void   tym_message__init
                     (TymMessage         *message);
size_t tym_message__get_packed_size
                     (const TymMessage   *message);
size_t tym_message__pack
                     (const TymMessage   *message,
                      uint8_t             *out);
size_t tym_message__pack_to_buffer
                     (const TymMessage   *message,
                      ProtobufCBuffer     *buffer);
TymMessage *
       tym_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tym_message__free_unpacked
                     (TymMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TymMessage_Closure)
                 (const TymMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tym_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_tym_2eproto__INCLUDED */
