/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: system/system.proto */

#ifndef PROTOBUF_C_system_2fsystem_2eproto__INCLUDED
#define PROTOBUF_C_system_2fsystem_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _System__Reboot System__Reboot;
typedef struct _System__PowerOn System__PowerOn;
typedef struct _System__PowerOff System__PowerOff;
typedef struct _System__PowerSupply System__PowerSupply;
typedef struct _System__ModeChanging System__ModeChanging;
typedef struct _System__GetUpgradeServerVersion System__GetUpgradeServerVersion;
typedef struct _System__UpgradeDownload System__UpgradeDownload;
typedef struct _System__UpgradeInstall System__UpgradeInstall;
typedef struct _System__UpgradeReboot System__UpgradeReboot;
typedef struct _System__Upgrading System__Upgrading;
typedef struct _System__Upgraded System__Upgraded;
typedef struct _System__FactoryReset System__FactoryReset;


/* --- enums --- */


/* --- messages --- */

/*
 * System reboot command message
 */
struct  _System__Reboot
{
  ProtobufCMessage base;
};
#define SYSTEM__REBOOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__reboot__descriptor) \
     }


/*
 * System power on command message
 */
struct  _System__PowerOn
{
  ProtobufCMessage base;
};
#define SYSTEM__POWER_ON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__power_on__descriptor) \
     }


/*
 * System power off command message
 */
struct  _System__PowerOff
{
  ProtobufCMessage base;
};
#define SYSTEM__POWER_OFF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__power_off__descriptor) \
     }


/*
 * Power supply source event message
 */
struct  _System__PowerSupply
{
  ProtobufCMessage base;
  char *source;
};
#define SYSTEM__POWER_SUPPLY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__power_supply__descriptor) \
    , NULL }


/*
 * Mode changing process event message
 */
struct  _System__ModeChanging
{
  ProtobufCMessage base;
  protobuf_c_boolean processing;
};
#define SYSTEM__MODE_CHANGING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__mode_changing__descriptor) \
    , 0 }


/*
 * Get upgrade server version command message
 */
struct  _System__GetUpgradeServerVersion
{
  ProtobufCMessage base;
};
#define SYSTEM__GET_UPGRADE_SERVER_VERSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__get_upgrade_server_version__descriptor) \
     }


/*
 * Upgrade download command message
 */
struct  _System__UpgradeDownload
{
  ProtobufCMessage base;
};
#define SYSTEM__UPGRADE_DOWNLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__upgrade_download__descriptor) \
     }


/*
 * Upgrade install command message
 */
struct  _System__UpgradeInstall
{
  ProtobufCMessage base;
};
#define SYSTEM__UPGRADE_INSTALL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__upgrade_install__descriptor) \
     }


/*
 * Upgrade reboot command message
 */
struct  _System__UpgradeReboot
{
  ProtobufCMessage base;
};
#define SYSTEM__UPGRADE_REBOOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__upgrade_reboot__descriptor) \
     }


/*
 * Upgrading process event message
 */
struct  _System__Upgrading
{
  ProtobufCMessage base;
};
#define SYSTEM__UPGRADING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__upgrading__descriptor) \
     }


/*
 * Upgrade result event message
 */
struct  _System__Upgraded
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define SYSTEM__UPGRADED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__upgraded__descriptor) \
    , 0 }


/*
 * Factory reset command message
 */
struct  _System__FactoryReset
{
  ProtobufCMessage base;
};
#define SYSTEM__FACTORY_RESET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&system__factory_reset__descriptor) \
     }


/* System__Reboot methods */
void   system__reboot__init
                     (System__Reboot         *message);
size_t system__reboot__get_packed_size
                     (const System__Reboot   *message);
size_t system__reboot__pack
                     (const System__Reboot   *message,
                      uint8_t             *out);
size_t system__reboot__pack_to_buffer
                     (const System__Reboot   *message,
                      ProtobufCBuffer     *buffer);
System__Reboot *
       system__reboot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__reboot__free_unpacked
                     (System__Reboot *message,
                      ProtobufCAllocator *allocator);
/* System__PowerOn methods */
void   system__power_on__init
                     (System__PowerOn         *message);
size_t system__power_on__get_packed_size
                     (const System__PowerOn   *message);
size_t system__power_on__pack
                     (const System__PowerOn   *message,
                      uint8_t             *out);
size_t system__power_on__pack_to_buffer
                     (const System__PowerOn   *message,
                      ProtobufCBuffer     *buffer);
System__PowerOn *
       system__power_on__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__power_on__free_unpacked
                     (System__PowerOn *message,
                      ProtobufCAllocator *allocator);
/* System__PowerOff methods */
void   system__power_off__init
                     (System__PowerOff         *message);
size_t system__power_off__get_packed_size
                     (const System__PowerOff   *message);
size_t system__power_off__pack
                     (const System__PowerOff   *message,
                      uint8_t             *out);
size_t system__power_off__pack_to_buffer
                     (const System__PowerOff   *message,
                      ProtobufCBuffer     *buffer);
System__PowerOff *
       system__power_off__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__power_off__free_unpacked
                     (System__PowerOff *message,
                      ProtobufCAllocator *allocator);
/* System__PowerSupply methods */
void   system__power_supply__init
                     (System__PowerSupply         *message);
size_t system__power_supply__get_packed_size
                     (const System__PowerSupply   *message);
size_t system__power_supply__pack
                     (const System__PowerSupply   *message,
                      uint8_t             *out);
size_t system__power_supply__pack_to_buffer
                     (const System__PowerSupply   *message,
                      ProtobufCBuffer     *buffer);
System__PowerSupply *
       system__power_supply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__power_supply__free_unpacked
                     (System__PowerSupply *message,
                      ProtobufCAllocator *allocator);
/* System__ModeChanging methods */
void   system__mode_changing__init
                     (System__ModeChanging         *message);
size_t system__mode_changing__get_packed_size
                     (const System__ModeChanging   *message);
size_t system__mode_changing__pack
                     (const System__ModeChanging   *message,
                      uint8_t             *out);
size_t system__mode_changing__pack_to_buffer
                     (const System__ModeChanging   *message,
                      ProtobufCBuffer     *buffer);
System__ModeChanging *
       system__mode_changing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__mode_changing__free_unpacked
                     (System__ModeChanging *message,
                      ProtobufCAllocator *allocator);
/* System__GetUpgradeServerVersion methods */
void   system__get_upgrade_server_version__init
                     (System__GetUpgradeServerVersion         *message);
size_t system__get_upgrade_server_version__get_packed_size
                     (const System__GetUpgradeServerVersion   *message);
size_t system__get_upgrade_server_version__pack
                     (const System__GetUpgradeServerVersion   *message,
                      uint8_t             *out);
size_t system__get_upgrade_server_version__pack_to_buffer
                     (const System__GetUpgradeServerVersion   *message,
                      ProtobufCBuffer     *buffer);
System__GetUpgradeServerVersion *
       system__get_upgrade_server_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__get_upgrade_server_version__free_unpacked
                     (System__GetUpgradeServerVersion *message,
                      ProtobufCAllocator *allocator);
/* System__UpgradeDownload methods */
void   system__upgrade_download__init
                     (System__UpgradeDownload         *message);
size_t system__upgrade_download__get_packed_size
                     (const System__UpgradeDownload   *message);
size_t system__upgrade_download__pack
                     (const System__UpgradeDownload   *message,
                      uint8_t             *out);
size_t system__upgrade_download__pack_to_buffer
                     (const System__UpgradeDownload   *message,
                      ProtobufCBuffer     *buffer);
System__UpgradeDownload *
       system__upgrade_download__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__upgrade_download__free_unpacked
                     (System__UpgradeDownload *message,
                      ProtobufCAllocator *allocator);
/* System__UpgradeInstall methods */
void   system__upgrade_install__init
                     (System__UpgradeInstall         *message);
size_t system__upgrade_install__get_packed_size
                     (const System__UpgradeInstall   *message);
size_t system__upgrade_install__pack
                     (const System__UpgradeInstall   *message,
                      uint8_t             *out);
size_t system__upgrade_install__pack_to_buffer
                     (const System__UpgradeInstall   *message,
                      ProtobufCBuffer     *buffer);
System__UpgradeInstall *
       system__upgrade_install__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__upgrade_install__free_unpacked
                     (System__UpgradeInstall *message,
                      ProtobufCAllocator *allocator);
/* System__UpgradeReboot methods */
void   system__upgrade_reboot__init
                     (System__UpgradeReboot         *message);
size_t system__upgrade_reboot__get_packed_size
                     (const System__UpgradeReboot   *message);
size_t system__upgrade_reboot__pack
                     (const System__UpgradeReboot   *message,
                      uint8_t             *out);
size_t system__upgrade_reboot__pack_to_buffer
                     (const System__UpgradeReboot   *message,
                      ProtobufCBuffer     *buffer);
System__UpgradeReboot *
       system__upgrade_reboot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__upgrade_reboot__free_unpacked
                     (System__UpgradeReboot *message,
                      ProtobufCAllocator *allocator);
/* System__Upgrading methods */
void   system__upgrading__init
                     (System__Upgrading         *message);
size_t system__upgrading__get_packed_size
                     (const System__Upgrading   *message);
size_t system__upgrading__pack
                     (const System__Upgrading   *message,
                      uint8_t             *out);
size_t system__upgrading__pack_to_buffer
                     (const System__Upgrading   *message,
                      ProtobufCBuffer     *buffer);
System__Upgrading *
       system__upgrading__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__upgrading__free_unpacked
                     (System__Upgrading *message,
                      ProtobufCAllocator *allocator);
/* System__Upgraded methods */
void   system__upgraded__init
                     (System__Upgraded         *message);
size_t system__upgraded__get_packed_size
                     (const System__Upgraded   *message);
size_t system__upgraded__pack
                     (const System__Upgraded   *message,
                      uint8_t             *out);
size_t system__upgraded__pack_to_buffer
                     (const System__Upgraded   *message,
                      ProtobufCBuffer     *buffer);
System__Upgraded *
       system__upgraded__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__upgraded__free_unpacked
                     (System__Upgraded *message,
                      ProtobufCAllocator *allocator);
/* System__FactoryReset methods */
void   system__factory_reset__init
                     (System__FactoryReset         *message);
size_t system__factory_reset__get_packed_size
                     (const System__FactoryReset   *message);
size_t system__factory_reset__pack
                     (const System__FactoryReset   *message,
                      uint8_t             *out);
size_t system__factory_reset__pack_to_buffer
                     (const System__FactoryReset   *message,
                      ProtobufCBuffer     *buffer);
System__FactoryReset *
       system__factory_reset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   system__factory_reset__free_unpacked
                     (System__FactoryReset *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*System__Reboot_Closure)
                 (const System__Reboot *message,
                  void *closure_data);
typedef void (*System__PowerOn_Closure)
                 (const System__PowerOn *message,
                  void *closure_data);
typedef void (*System__PowerOff_Closure)
                 (const System__PowerOff *message,
                  void *closure_data);
typedef void (*System__PowerSupply_Closure)
                 (const System__PowerSupply *message,
                  void *closure_data);
typedef void (*System__ModeChanging_Closure)
                 (const System__ModeChanging *message,
                  void *closure_data);
typedef void (*System__GetUpgradeServerVersion_Closure)
                 (const System__GetUpgradeServerVersion *message,
                  void *closure_data);
typedef void (*System__UpgradeDownload_Closure)
                 (const System__UpgradeDownload *message,
                  void *closure_data);
typedef void (*System__UpgradeInstall_Closure)
                 (const System__UpgradeInstall *message,
                  void *closure_data);
typedef void (*System__UpgradeReboot_Closure)
                 (const System__UpgradeReboot *message,
                  void *closure_data);
typedef void (*System__Upgrading_Closure)
                 (const System__Upgrading *message,
                  void *closure_data);
typedef void (*System__Upgraded_Closure)
                 (const System__Upgraded *message,
                  void *closure_data);
typedef void (*System__FactoryReset_Closure)
                 (const System__FactoryReset *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor system__reboot__descriptor;
extern const ProtobufCMessageDescriptor system__power_on__descriptor;
extern const ProtobufCMessageDescriptor system__power_off__descriptor;
extern const ProtobufCMessageDescriptor system__power_supply__descriptor;
extern const ProtobufCMessageDescriptor system__mode_changing__descriptor;
extern const ProtobufCMessageDescriptor system__get_upgrade_server_version__descriptor;
extern const ProtobufCMessageDescriptor system__upgrade_download__descriptor;
extern const ProtobufCMessageDescriptor system__upgrade_install__descriptor;
extern const ProtobufCMessageDescriptor system__upgrade_reboot__descriptor;
extern const ProtobufCMessageDescriptor system__upgrading__descriptor;
extern const ProtobufCMessageDescriptor system__upgraded__descriptor;
extern const ProtobufCMessageDescriptor system__factory_reset__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_system_2fsystem_2eproto__INCLUDED */
