/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: devices/devices.proto */

#ifndef PROTOBUF_C_devices_2fdevices_2eproto__INCLUDED
#define PROTOBUF_C_devices_2fdevices_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Devices__UltrasonicStatus Devices__UltrasonicStatus;
typedef struct _Devices__ChargingState Devices__ChargingState;
typedef struct _Devices__ChargingProtect Devices__ChargingProtect;
typedef struct _Devices__BatLevelLow Devices__BatLevelLow;
typedef struct _Devices__DisplaySet Devices__DisplaySet;


/* --- enums --- */


/* --- messages --- */

/*
 * Ultrasonic status event message
 */
struct  _Devices__UltrasonicStatus
{
  ProtobufCMessage base;
  int32_t status;
  int32_t flag;
};
#define DEVICES__ULTRASONIC_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&devices__ultrasonic_status__descriptor) \
    , 0, 0 }


/*
 * Charging state event message
 */
struct  _Devices__ChargingState
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define DEVICES__CHARGING_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&devices__charging_state__descriptor) \
    , 0 }


/*
 * Charging protect event message
 */
struct  _Devices__ChargingProtect
{
  ProtobufCMessage base;
  int32_t level;
};
#define DEVICES__CHARGING_PROTECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&devices__charging_protect__descriptor) \
    , 0 }


/*
 * Battery level low event message
 */
struct  _Devices__BatLevelLow
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define DEVICES__BAT_LEVEL_LOW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&devices__bat_level_low__descriptor) \
    , 0 }


/*
 * Display set command message
 */
struct  _Devices__DisplaySet
{
  ProtobufCMessage base;
  char *value;
};
#define DEVICES__DISPLAY_SET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&devices__display_set__descriptor) \
    , NULL }


/* Devices__UltrasonicStatus methods */
void   devices__ultrasonic_status__init
                     (Devices__UltrasonicStatus         *message);
size_t devices__ultrasonic_status__get_packed_size
                     (const Devices__UltrasonicStatus   *message);
size_t devices__ultrasonic_status__pack
                     (const Devices__UltrasonicStatus   *message,
                      uint8_t             *out);
size_t devices__ultrasonic_status__pack_to_buffer
                     (const Devices__UltrasonicStatus   *message,
                      ProtobufCBuffer     *buffer);
Devices__UltrasonicStatus *
       devices__ultrasonic_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   devices__ultrasonic_status__free_unpacked
                     (Devices__UltrasonicStatus *message,
                      ProtobufCAllocator *allocator);
/* Devices__ChargingState methods */
void   devices__charging_state__init
                     (Devices__ChargingState         *message);
size_t devices__charging_state__get_packed_size
                     (const Devices__ChargingState   *message);
size_t devices__charging_state__pack
                     (const Devices__ChargingState   *message,
                      uint8_t             *out);
size_t devices__charging_state__pack_to_buffer
                     (const Devices__ChargingState   *message,
                      ProtobufCBuffer     *buffer);
Devices__ChargingState *
       devices__charging_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   devices__charging_state__free_unpacked
                     (Devices__ChargingState *message,
                      ProtobufCAllocator *allocator);
/* Devices__ChargingProtect methods */
void   devices__charging_protect__init
                     (Devices__ChargingProtect         *message);
size_t devices__charging_protect__get_packed_size
                     (const Devices__ChargingProtect   *message);
size_t devices__charging_protect__pack
                     (const Devices__ChargingProtect   *message,
                      uint8_t             *out);
size_t devices__charging_protect__pack_to_buffer
                     (const Devices__ChargingProtect   *message,
                      ProtobufCBuffer     *buffer);
Devices__ChargingProtect *
       devices__charging_protect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   devices__charging_protect__free_unpacked
                     (Devices__ChargingProtect *message,
                      ProtobufCAllocator *allocator);
/* Devices__BatLevelLow methods */
void   devices__bat_level_low__init
                     (Devices__BatLevelLow         *message);
size_t devices__bat_level_low__get_packed_size
                     (const Devices__BatLevelLow   *message);
size_t devices__bat_level_low__pack
                     (const Devices__BatLevelLow   *message,
                      uint8_t             *out);
size_t devices__bat_level_low__pack_to_buffer
                     (const Devices__BatLevelLow   *message,
                      ProtobufCBuffer     *buffer);
Devices__BatLevelLow *
       devices__bat_level_low__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   devices__bat_level_low__free_unpacked
                     (Devices__BatLevelLow *message,
                      ProtobufCAllocator *allocator);
/* Devices__DisplaySet methods */
void   devices__display_set__init
                     (Devices__DisplaySet         *message);
size_t devices__display_set__get_packed_size
                     (const Devices__DisplaySet   *message);
size_t devices__display_set__pack
                     (const Devices__DisplaySet   *message,
                      uint8_t             *out);
size_t devices__display_set__pack_to_buffer
                     (const Devices__DisplaySet   *message,
                      ProtobufCBuffer     *buffer);
Devices__DisplaySet *
       devices__display_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   devices__display_set__free_unpacked
                     (Devices__DisplaySet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Devices__UltrasonicStatus_Closure)
                 (const Devices__UltrasonicStatus *message,
                  void *closure_data);
typedef void (*Devices__ChargingState_Closure)
                 (const Devices__ChargingState *message,
                  void *closure_data);
typedef void (*Devices__ChargingProtect_Closure)
                 (const Devices__ChargingProtect *message,
                  void *closure_data);
typedef void (*Devices__BatLevelLow_Closure)
                 (const Devices__BatLevelLow *message,
                  void *closure_data);
typedef void (*Devices__DisplaySet_Closure)
                 (const Devices__DisplaySet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor devices__ultrasonic_status__descriptor;
extern const ProtobufCMessageDescriptor devices__charging_state__descriptor;
extern const ProtobufCMessageDescriptor devices__charging_protect__descriptor;
extern const ProtobufCMessageDescriptor devices__bat_level_low__descriptor;
extern const ProtobufCMessageDescriptor devices__display_set__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_devices_2fdevices_2eproto__INCLUDED */
