/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: connectivity/connectivity.proto */

#ifndef PROTOBUF_C_connectivity_2fconnectivity_2eproto__INCLUDED
#define PROTOBUF_C_connectivity_2fconnectivity_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Connectivity__BtEnabled Connectivity__BtEnabled;
typedef struct _Connectivity__BtPairing Connectivity__BtPairing;
typedef struct _Connectivity__BtConnected Connectivity__BtConnected;
typedef struct _Connectivity__WifiConnected Connectivity__WifiConnected;
typedef struct _Connectivity__WifiConnect Connectivity__WifiConnect;
typedef struct _Connectivity__WifiScan Connectivity__WifiScan;
typedef struct _Connectivity__WifiScanResult Connectivity__WifiScanResult;
typedef struct _Connectivity__WifiOnboard Connectivity__WifiOnboard;
typedef struct _Connectivity__WifiOnboarded Connectivity__WifiOnboarded;
typedef struct _Connectivity__WifiError Connectivity__WifiError;
typedef struct _Connectivity__BtEnable Connectivity__BtEnable;
typedef struct _Connectivity__BtDisable Connectivity__BtDisable;
typedef struct _Connectivity__BtUnpair Connectivity__BtUnpair;
typedef struct _Connectivity__SelfBtEnabled Connectivity__SelfBtEnabled;
typedef struct _Connectivity__SelfBtPairing Connectivity__SelfBtPairing;
typedef struct _Connectivity__SelfBtConnected Connectivity__SelfBtConnected;
typedef struct _Connectivity__SelfWifiConnecting Connectivity__SelfWifiConnecting;
typedef struct _Connectivity__SelfWifiConnected Connectivity__SelfWifiConnected;
typedef struct _Connectivity__SelfWifiDisconnected Connectivity__SelfWifiDisconnected;


/* --- enums --- */


/* --- messages --- */

/*
 * Bluetooth enabled state event message
 */
struct  _Connectivity__BtEnabled
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define CONNECTIVITY__BT_ENABLED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__bt_enabled__descriptor) \
    , 0 }


/*
 * Bluetooth pairing state event message
 */
struct  _Connectivity__BtPairing
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define CONNECTIVITY__BT_PAIRING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__bt_pairing__descriptor) \
    , 0 }


/*
 * Bluetooth connected state event message
 */
struct  _Connectivity__BtConnected
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define CONNECTIVITY__BT_CONNECTED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__bt_connected__descriptor) \
    , 0 }


/*
 * Wi-Fi connected state event message
 */
struct  _Connectivity__WifiConnected
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define CONNECTIVITY__WIFI_CONNECTED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__wifi_connected__descriptor) \
    , 0 }


/*
 * Wi-Fi connect command message
 */
struct  _Connectivity__WifiConnect
{
  ProtobufCMessage base;
  char *ssid;
  char *psk;
};
#define CONNECTIVITY__WIFI_CONNECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__wifi_connect__descriptor) \
    , NULL, NULL }


/*
 * Wi-Fi scan command message
 */
struct  _Connectivity__WifiScan
{
  ProtobufCMessage base;
};
#define CONNECTIVITY__WIFI_SCAN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__wifi_scan__descriptor) \
     }


/*
 * Wi-Fi scan result event message
 */
struct  _Connectivity__WifiScanResult
{
  ProtobufCMessage base;
  char *wifilist;
};
#define CONNECTIVITY__WIFI_SCAN_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__wifi_scan_result__descriptor) \
    , NULL }


/*
 * Wi-Fi onboard command message
 */
struct  _Connectivity__WifiOnboard
{
  ProtobufCMessage base;
};
#define CONNECTIVITY__WIFI_ONBOARD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__wifi_onboard__descriptor) \
     }


/*
 * Wi-Fi onboarded state event message
 */
struct  _Connectivity__WifiOnboarded
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define CONNECTIVITY__WIFI_ONBOARDED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__wifi_onboarded__descriptor) \
    , 0 }


/*
 * Wi-Fi error event message
 */
struct  _Connectivity__WifiError
{
  ProtobufCMessage base;
  int32_t error_code;
};
#define CONNECTIVITY__WIFI_ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__wifi_error__descriptor) \
    , 0 }


/*
 * Bluetooth enable command message
 */
struct  _Connectivity__BtEnable
{
  ProtobufCMessage base;
};
#define CONNECTIVITY__BT_ENABLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__bt_enable__descriptor) \
     }


/*
 * Bluetooth disable command message
 */
struct  _Connectivity__BtDisable
{
  ProtobufCMessage base;
};
#define CONNECTIVITY__BT_DISABLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__bt_disable__descriptor) \
     }


/*
 * Bluetooth unpair command message
 */
struct  _Connectivity__BtUnpair
{
  ProtobufCMessage base;
};
#define CONNECTIVITY__BT_UNPAIR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__bt_unpair__descriptor) \
     }


/*
 * Self Bluetooth enabled state event message
 */
struct  _Connectivity__SelfBtEnabled
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define CONNECTIVITY__SELF_BT_ENABLED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__self_bt_enabled__descriptor) \
    , 0 }


/*
 * Self Bluetooth pairing state event message
 */
struct  _Connectivity__SelfBtPairing
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define CONNECTIVITY__SELF_BT_PAIRING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__self_bt_pairing__descriptor) \
    , 0 }


/*
 * Self Bluetooth connected state event message
 */
struct  _Connectivity__SelfBtConnected
{
  ProtobufCMessage base;
  protobuf_c_boolean state;
};
#define CONNECTIVITY__SELF_BT_CONNECTED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__self_bt_connected__descriptor) \
    , 0 }


/*
 * Self Wi-Fi connecting state event message
 */
struct  _Connectivity__SelfWifiConnecting
{
  ProtobufCMessage base;
};
#define CONNECTIVITY__SELF_WIFI_CONNECTING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__self_wifi_connecting__descriptor) \
     }


/*
 * Self Wi-Fi connected state event message
 */
struct  _Connectivity__SelfWifiConnected
{
  ProtobufCMessage base;
};
#define CONNECTIVITY__SELF_WIFI_CONNECTED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__self_wifi_connected__descriptor) \
     }


/*
 * Self Wi-Fi disconnected state event message
 */
struct  _Connectivity__SelfWifiDisconnected
{
  ProtobufCMessage base;
};
#define CONNECTIVITY__SELF_WIFI_DISCONNECTED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&connectivity__self_wifi_disconnected__descriptor) \
     }


/* Connectivity__BtEnabled methods */
void   connectivity__bt_enabled__init
                     (Connectivity__BtEnabled         *message);
size_t connectivity__bt_enabled__get_packed_size
                     (const Connectivity__BtEnabled   *message);
size_t connectivity__bt_enabled__pack
                     (const Connectivity__BtEnabled   *message,
                      uint8_t             *out);
size_t connectivity__bt_enabled__pack_to_buffer
                     (const Connectivity__BtEnabled   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__BtEnabled *
       connectivity__bt_enabled__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__bt_enabled__free_unpacked
                     (Connectivity__BtEnabled *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__BtPairing methods */
void   connectivity__bt_pairing__init
                     (Connectivity__BtPairing         *message);
size_t connectivity__bt_pairing__get_packed_size
                     (const Connectivity__BtPairing   *message);
size_t connectivity__bt_pairing__pack
                     (const Connectivity__BtPairing   *message,
                      uint8_t             *out);
size_t connectivity__bt_pairing__pack_to_buffer
                     (const Connectivity__BtPairing   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__BtPairing *
       connectivity__bt_pairing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__bt_pairing__free_unpacked
                     (Connectivity__BtPairing *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__BtConnected methods */
void   connectivity__bt_connected__init
                     (Connectivity__BtConnected         *message);
size_t connectivity__bt_connected__get_packed_size
                     (const Connectivity__BtConnected   *message);
size_t connectivity__bt_connected__pack
                     (const Connectivity__BtConnected   *message,
                      uint8_t             *out);
size_t connectivity__bt_connected__pack_to_buffer
                     (const Connectivity__BtConnected   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__BtConnected *
       connectivity__bt_connected__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__bt_connected__free_unpacked
                     (Connectivity__BtConnected *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__WifiConnected methods */
void   connectivity__wifi_connected__init
                     (Connectivity__WifiConnected         *message);
size_t connectivity__wifi_connected__get_packed_size
                     (const Connectivity__WifiConnected   *message);
size_t connectivity__wifi_connected__pack
                     (const Connectivity__WifiConnected   *message,
                      uint8_t             *out);
size_t connectivity__wifi_connected__pack_to_buffer
                     (const Connectivity__WifiConnected   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__WifiConnected *
       connectivity__wifi_connected__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__wifi_connected__free_unpacked
                     (Connectivity__WifiConnected *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__WifiConnect methods */
void   connectivity__wifi_connect__init
                     (Connectivity__WifiConnect         *message);
size_t connectivity__wifi_connect__get_packed_size
                     (const Connectivity__WifiConnect   *message);
size_t connectivity__wifi_connect__pack
                     (const Connectivity__WifiConnect   *message,
                      uint8_t             *out);
size_t connectivity__wifi_connect__pack_to_buffer
                     (const Connectivity__WifiConnect   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__WifiConnect *
       connectivity__wifi_connect__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__wifi_connect__free_unpacked
                     (Connectivity__WifiConnect *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__WifiScan methods */
void   connectivity__wifi_scan__init
                     (Connectivity__WifiScan         *message);
size_t connectivity__wifi_scan__get_packed_size
                     (const Connectivity__WifiScan   *message);
size_t connectivity__wifi_scan__pack
                     (const Connectivity__WifiScan   *message,
                      uint8_t             *out);
size_t connectivity__wifi_scan__pack_to_buffer
                     (const Connectivity__WifiScan   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__WifiScan *
       connectivity__wifi_scan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__wifi_scan__free_unpacked
                     (Connectivity__WifiScan *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__WifiScanResult methods */
void   connectivity__wifi_scan_result__init
                     (Connectivity__WifiScanResult         *message);
size_t connectivity__wifi_scan_result__get_packed_size
                     (const Connectivity__WifiScanResult   *message);
size_t connectivity__wifi_scan_result__pack
                     (const Connectivity__WifiScanResult   *message,
                      uint8_t             *out);
size_t connectivity__wifi_scan_result__pack_to_buffer
                     (const Connectivity__WifiScanResult   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__WifiScanResult *
       connectivity__wifi_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__wifi_scan_result__free_unpacked
                     (Connectivity__WifiScanResult *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__WifiOnboard methods */
void   connectivity__wifi_onboard__init
                     (Connectivity__WifiOnboard         *message);
size_t connectivity__wifi_onboard__get_packed_size
                     (const Connectivity__WifiOnboard   *message);
size_t connectivity__wifi_onboard__pack
                     (const Connectivity__WifiOnboard   *message,
                      uint8_t             *out);
size_t connectivity__wifi_onboard__pack_to_buffer
                     (const Connectivity__WifiOnboard   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__WifiOnboard *
       connectivity__wifi_onboard__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__wifi_onboard__free_unpacked
                     (Connectivity__WifiOnboard *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__WifiOnboarded methods */
void   connectivity__wifi_onboarded__init
                     (Connectivity__WifiOnboarded         *message);
size_t connectivity__wifi_onboarded__get_packed_size
                     (const Connectivity__WifiOnboarded   *message);
size_t connectivity__wifi_onboarded__pack
                     (const Connectivity__WifiOnboarded   *message,
                      uint8_t             *out);
size_t connectivity__wifi_onboarded__pack_to_buffer
                     (const Connectivity__WifiOnboarded   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__WifiOnboarded *
       connectivity__wifi_onboarded__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__wifi_onboarded__free_unpacked
                     (Connectivity__WifiOnboarded *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__WifiError methods */
void   connectivity__wifi_error__init
                     (Connectivity__WifiError         *message);
size_t connectivity__wifi_error__get_packed_size
                     (const Connectivity__WifiError   *message);
size_t connectivity__wifi_error__pack
                     (const Connectivity__WifiError   *message,
                      uint8_t             *out);
size_t connectivity__wifi_error__pack_to_buffer
                     (const Connectivity__WifiError   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__WifiError *
       connectivity__wifi_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__wifi_error__free_unpacked
                     (Connectivity__WifiError *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__BtEnable methods */
void   connectivity__bt_enable__init
                     (Connectivity__BtEnable         *message);
size_t connectivity__bt_enable__get_packed_size
                     (const Connectivity__BtEnable   *message);
size_t connectivity__bt_enable__pack
                     (const Connectivity__BtEnable   *message,
                      uint8_t             *out);
size_t connectivity__bt_enable__pack_to_buffer
                     (const Connectivity__BtEnable   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__BtEnable *
       connectivity__bt_enable__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__bt_enable__free_unpacked
                     (Connectivity__BtEnable *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__BtDisable methods */
void   connectivity__bt_disable__init
                     (Connectivity__BtDisable         *message);
size_t connectivity__bt_disable__get_packed_size
                     (const Connectivity__BtDisable   *message);
size_t connectivity__bt_disable__pack
                     (const Connectivity__BtDisable   *message,
                      uint8_t             *out);
size_t connectivity__bt_disable__pack_to_buffer
                     (const Connectivity__BtDisable   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__BtDisable *
       connectivity__bt_disable__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__bt_disable__free_unpacked
                     (Connectivity__BtDisable *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__BtUnpair methods */
void   connectivity__bt_unpair__init
                     (Connectivity__BtUnpair         *message);
size_t connectivity__bt_unpair__get_packed_size
                     (const Connectivity__BtUnpair   *message);
size_t connectivity__bt_unpair__pack
                     (const Connectivity__BtUnpair   *message,
                      uint8_t             *out);
size_t connectivity__bt_unpair__pack_to_buffer
                     (const Connectivity__BtUnpair   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__BtUnpair *
       connectivity__bt_unpair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__bt_unpair__free_unpacked
                     (Connectivity__BtUnpair *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__SelfBtEnabled methods */
void   connectivity__self_bt_enabled__init
                     (Connectivity__SelfBtEnabled         *message);
size_t connectivity__self_bt_enabled__get_packed_size
                     (const Connectivity__SelfBtEnabled   *message);
size_t connectivity__self_bt_enabled__pack
                     (const Connectivity__SelfBtEnabled   *message,
                      uint8_t             *out);
size_t connectivity__self_bt_enabled__pack_to_buffer
                     (const Connectivity__SelfBtEnabled   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__SelfBtEnabled *
       connectivity__self_bt_enabled__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__self_bt_enabled__free_unpacked
                     (Connectivity__SelfBtEnabled *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__SelfBtPairing methods */
void   connectivity__self_bt_pairing__init
                     (Connectivity__SelfBtPairing         *message);
size_t connectivity__self_bt_pairing__get_packed_size
                     (const Connectivity__SelfBtPairing   *message);
size_t connectivity__self_bt_pairing__pack
                     (const Connectivity__SelfBtPairing   *message,
                      uint8_t             *out);
size_t connectivity__self_bt_pairing__pack_to_buffer
                     (const Connectivity__SelfBtPairing   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__SelfBtPairing *
       connectivity__self_bt_pairing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__self_bt_pairing__free_unpacked
                     (Connectivity__SelfBtPairing *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__SelfBtConnected methods */
void   connectivity__self_bt_connected__init
                     (Connectivity__SelfBtConnected         *message);
size_t connectivity__self_bt_connected__get_packed_size
                     (const Connectivity__SelfBtConnected   *message);
size_t connectivity__self_bt_connected__pack
                     (const Connectivity__SelfBtConnected   *message,
                      uint8_t             *out);
size_t connectivity__self_bt_connected__pack_to_buffer
                     (const Connectivity__SelfBtConnected   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__SelfBtConnected *
       connectivity__self_bt_connected__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__self_bt_connected__free_unpacked
                     (Connectivity__SelfBtConnected *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__SelfWifiConnecting methods */
void   connectivity__self_wifi_connecting__init
                     (Connectivity__SelfWifiConnecting         *message);
size_t connectivity__self_wifi_connecting__get_packed_size
                     (const Connectivity__SelfWifiConnecting   *message);
size_t connectivity__self_wifi_connecting__pack
                     (const Connectivity__SelfWifiConnecting   *message,
                      uint8_t             *out);
size_t connectivity__self_wifi_connecting__pack_to_buffer
                     (const Connectivity__SelfWifiConnecting   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__SelfWifiConnecting *
       connectivity__self_wifi_connecting__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__self_wifi_connecting__free_unpacked
                     (Connectivity__SelfWifiConnecting *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__SelfWifiConnected methods */
void   connectivity__self_wifi_connected__init
                     (Connectivity__SelfWifiConnected         *message);
size_t connectivity__self_wifi_connected__get_packed_size
                     (const Connectivity__SelfWifiConnected   *message);
size_t connectivity__self_wifi_connected__pack
                     (const Connectivity__SelfWifiConnected   *message,
                      uint8_t             *out);
size_t connectivity__self_wifi_connected__pack_to_buffer
                     (const Connectivity__SelfWifiConnected   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__SelfWifiConnected *
       connectivity__self_wifi_connected__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__self_wifi_connected__free_unpacked
                     (Connectivity__SelfWifiConnected *message,
                      ProtobufCAllocator *allocator);
/* Connectivity__SelfWifiDisconnected methods */
void   connectivity__self_wifi_disconnected__init
                     (Connectivity__SelfWifiDisconnected         *message);
size_t connectivity__self_wifi_disconnected__get_packed_size
                     (const Connectivity__SelfWifiDisconnected   *message);
size_t connectivity__self_wifi_disconnected__pack
                     (const Connectivity__SelfWifiDisconnected   *message,
                      uint8_t             *out);
size_t connectivity__self_wifi_disconnected__pack_to_buffer
                     (const Connectivity__SelfWifiDisconnected   *message,
                      ProtobufCBuffer     *buffer);
Connectivity__SelfWifiDisconnected *
       connectivity__self_wifi_disconnected__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   connectivity__self_wifi_disconnected__free_unpacked
                     (Connectivity__SelfWifiDisconnected *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Connectivity__BtEnabled_Closure)
                 (const Connectivity__BtEnabled *message,
                  void *closure_data);
typedef void (*Connectivity__BtPairing_Closure)
                 (const Connectivity__BtPairing *message,
                  void *closure_data);
typedef void (*Connectivity__BtConnected_Closure)
                 (const Connectivity__BtConnected *message,
                  void *closure_data);
typedef void (*Connectivity__WifiConnected_Closure)
                 (const Connectivity__WifiConnected *message,
                  void *closure_data);
typedef void (*Connectivity__WifiConnect_Closure)
                 (const Connectivity__WifiConnect *message,
                  void *closure_data);
typedef void (*Connectivity__WifiScan_Closure)
                 (const Connectivity__WifiScan *message,
                  void *closure_data);
typedef void (*Connectivity__WifiScanResult_Closure)
                 (const Connectivity__WifiScanResult *message,
                  void *closure_data);
typedef void (*Connectivity__WifiOnboard_Closure)
                 (const Connectivity__WifiOnboard *message,
                  void *closure_data);
typedef void (*Connectivity__WifiOnboarded_Closure)
                 (const Connectivity__WifiOnboarded *message,
                  void *closure_data);
typedef void (*Connectivity__WifiError_Closure)
                 (const Connectivity__WifiError *message,
                  void *closure_data);
typedef void (*Connectivity__BtEnable_Closure)
                 (const Connectivity__BtEnable *message,
                  void *closure_data);
typedef void (*Connectivity__BtDisable_Closure)
                 (const Connectivity__BtDisable *message,
                  void *closure_data);
typedef void (*Connectivity__BtUnpair_Closure)
                 (const Connectivity__BtUnpair *message,
                  void *closure_data);
typedef void (*Connectivity__SelfBtEnabled_Closure)
                 (const Connectivity__SelfBtEnabled *message,
                  void *closure_data);
typedef void (*Connectivity__SelfBtPairing_Closure)
                 (const Connectivity__SelfBtPairing *message,
                  void *closure_data);
typedef void (*Connectivity__SelfBtConnected_Closure)
                 (const Connectivity__SelfBtConnected *message,
                  void *closure_data);
typedef void (*Connectivity__SelfWifiConnecting_Closure)
                 (const Connectivity__SelfWifiConnecting *message,
                  void *closure_data);
typedef void (*Connectivity__SelfWifiConnected_Closure)
                 (const Connectivity__SelfWifiConnected *message,
                  void *closure_data);
typedef void (*Connectivity__SelfWifiDisconnected_Closure)
                 (const Connectivity__SelfWifiDisconnected *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor connectivity__bt_enabled__descriptor;
extern const ProtobufCMessageDescriptor connectivity__bt_pairing__descriptor;
extern const ProtobufCMessageDescriptor connectivity__bt_connected__descriptor;
extern const ProtobufCMessageDescriptor connectivity__wifi_connected__descriptor;
extern const ProtobufCMessageDescriptor connectivity__wifi_connect__descriptor;
extern const ProtobufCMessageDescriptor connectivity__wifi_scan__descriptor;
extern const ProtobufCMessageDescriptor connectivity__wifi_scan_result__descriptor;
extern const ProtobufCMessageDescriptor connectivity__wifi_onboard__descriptor;
extern const ProtobufCMessageDescriptor connectivity__wifi_onboarded__descriptor;
extern const ProtobufCMessageDescriptor connectivity__wifi_error__descriptor;
extern const ProtobufCMessageDescriptor connectivity__bt_enable__descriptor;
extern const ProtobufCMessageDescriptor connectivity__bt_disable__descriptor;
extern const ProtobufCMessageDescriptor connectivity__bt_unpair__descriptor;
extern const ProtobufCMessageDescriptor connectivity__self_bt_enabled__descriptor;
extern const ProtobufCMessageDescriptor connectivity__self_bt_pairing__descriptor;
extern const ProtobufCMessageDescriptor connectivity__self_bt_connected__descriptor;
extern const ProtobufCMessageDescriptor connectivity__self_wifi_connecting__descriptor;
extern const ProtobufCMessageDescriptor connectivity__self_wifi_connected__descriptor;
extern const ProtobufCMessageDescriptor connectivity__self_wifi_disconnected__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_connectivity_2fconnectivity_2eproto__INCLUDED */
